apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: testksc-dev-triggerbinding
  namespace: testksc-dev
  labels:
    app.kubernetes.io/instance: cluster-configs
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.url)
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-application-name
      value: $(body.repository.name)
